# Generated by Django 4.2 on 2023-04-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('monto_solicitado', models.PositiveIntegerField(default=1000)),
                ('aprobado', models.BooleanField(default=False)),
                ('respuesta_api', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
